--!strict
--[[
	Strings
	------------------------------------------------------------------
	Los tres idiomas del juego. El servidor NUNCA manda texto armado:
	manda { key = "notify.passed", args = { grade = "B" } } y el cliente
	lo dibuja con el idioma que tiene cada jugador en su Roblox.

	Regla: las tres tablas tienen exactamente las mismas claves.
	tools/check.py lo verifica antes de empaquetar.
--]]

local Strings = {}

local en: { [string]: string } = {
	-- Fases del dia
	["phase.espera"] = "Waiting for students",
	["phase.recreo"] = "Recess",
	["phase.examen"] = "Exam",
	["phase.boletin"] = "Report cards",
	["phase.intermedio"] = "Between classes",
	["phase.semana"] = "Finals Week",
	["day.lunes"] = "Monday",
	["day.martes"] = "Tuesday",
	["day.miercoles"] = "Wednesday",
	["day.jueves"] = "Thursday",
	["day.viernes"] = "Friday",
	-- HUD
	["hud.day"] = "Day {n} - {day}",
	["hud.suspicion"] = "SUSPICION",
	["hud.grade"] = "TERM GRADE",
	["hud.credits"] = "CREDITS",
	["hud.objective"] = "OBJECTIVE",
	["hud.close_call"] = "THE TEACHER IS WATCHING YOU",
	["hud.locked"] = "Doors locked",
	["hud.hint_recess"] = "Grab what you need before the bell",
	["hud.hint_exam"] = "Answer the sheet on your desk",
	["hud.hint_report"] = "Report cards are out",
	["hud.detention"] = "Detention: {s}s",
	["hud.cone"] = "Dunce cone: {s}s",
	["hud.keys"] = "E interact - Q peek - R whisper - F throw - G shove - B shoot - Z zoom",
	-- Examen
	["exam.title"] = "Exam - {subject}",
	["exam.question"] = "Question {i} of {n}",
	["exam.progress"] = "{done}/{total} answered",
	["exam.answered"] = "Answered",
	["exam.blank"] = "Blank",
	["exam.correct"] = "Correct",
	["exam.wrong"] = "Wrong",
	["exam.type_prompt"] = "Type the sequence",
	["exam.type_fail"] = "You mistyped it",
	["exam.time_up"] = "Pencils down",
	["exam.not_started"] = "The exam has not started",
	["exam.prev"] = "Previous",
	["exam.next"] = "Next",
	["topic.math"] = "Mathematics",
	["topic.history"] = "History",
	["topic.science"] = "Science",
	["topic.language"] = "Language",
	["topic.geography"] = "Geography",
	-- Trampas
	["cheat.peek"] = "Peek at a classmate's sheet",
	["cheat.peek_ok"] = "You copied question {i}",
	["cheat.peek_fail"] = "You couldn't read anything",
	["cheat.peek_none"] = "Nobody is sitting close enough",
	["cheat.whisper"] = "Whisper an answer",
	["cheat.whisper_sent"] = "You whispered question {i}",
	["cheat.whisper_got"] = "{name} whispers: {i} is {opt}",
	["cheat.sheet_used"] = "Cheat sheet: {n} answers revealed",
	["cheat.sheet_empty"] = "The cheat sheet is used up",
	["stash.drawer"] = "You raided the drawer: {n} answers",
	["stash.alcove"] = "The answer key: {n} answers learned",
	["stash.empty"] = "There is nothing in there",
	["stash.locked"] = "The library is closed during the exam",
	["stash.cooling"] = "Not so fast",
	["cheat.cooldown"] = "Wait a moment",
	["cheat.seen"] = "The teacher saw you",
	["cheat.none"] = "You have nothing to use",
	-- Objetos
	["item.nota"] = "Note",
	["item.avion"] = "Paper plane",
	["item.bolita"] = "Paper ball",
	["item.chuleta"] = "Cheat sheet",
	["item.gorra"] = "Cap",
	["item.mochila"] = "Backpack",
	["item.anteojos"] = "Glasses",
	["item.campera"] = "Jacket",
	["item.desc_nota"] = "Write an answer and throw it to a classmate",
	["item.desc_avion"] = "Flies further and straighter than the ball",
	["item.desc_bolita"] = "Throw it far away: the teacher goes to the noise",
	["item.desc_chuleta"] = "Reveals {n} answers of the current exam",
	["item.desc_gorra"] = "A cap. It does nothing. It looks good.",
	["item.desc_mochila"] = "Classic school backpack",
	["item.desc_anteojos"] = "You look like you study",
	["item.desc_campera"] = "School jacket with the crest",
	-- Notas de papel
	["note.write"] = "Write your note",
	["note.placeholder"] = "3 is B, 5 is A...",
	["note.throw"] = "Aim and click to throw",
	["note.sent"] = "Note thrown",
	["note.received"] = "{name} passed you a note",
	["note.empty"] = "The note is blank",
	["note.read"] = "The note says:",
	-- Tienda
	["shop.title"] = "School store",
	["shop.buy"] = "Buy",
	["shop.owned"] = "Owned",
	["shop.locked"] = "Locked",
	["shop.need_weeks"] = "Survive {n} finals weeks first",
	["shop.need_grade"] = "Reach a {n} average first",
	["shop.equip"] = "Equip",
	["shop.equipped"] = "Equipped",
	["shop.cannot"] = "Not enough credits",
	["shop.bought"] = "You bought {item}",
	["shop.closed"] = "The store only opens at recess",
	["shop.tab_items"] = "Gear",
	["shop.tab_looks"] = "Looks",
	["shop.price"] = "{n} cr",
	-- El profesor
	["teacher.greet"] = "Sit down. Now.",
	["teacher.start_exam"] = "You have {s} seconds. Do not talk.",
	["teacher.silence"] = "Silence.",
	["teacher.sit_down"] = "Back to your seat.",
	["teacher.eyes_on_paper"] = "Eyes on your own paper.",
	["teacher.caught"] = "I saw that, {name}.",
	["teacher.warning"] = "Last warning.",
	["teacher.blackboard"] = "Copy this down.",
	["teacher.time_left"] = "{s} seconds left.",
	["teacher.finish"] = "Pencils down. Papers up.",
	["teacher.noise"] = "Who threw that?",
	-- Castigos
	["punish.cone"] = "{name} got the dunce cone",
	["punish.grade"] = "-{n} points off your grade",
	["punish.detention"] = "{name} was sent to detention",
	["punish.warned"] = "Final warning",
	["punish.back"] = "You are back in class",
	-- Avisos
	["notify.bell"] = "The bell rang",
	["notify.bell_soon"] = "The bell rings in {s}s",
	["notify.doors_locked"] = "The classroom doors locked",
	["notify.exam_start"] = "The exam started",
	["notify.exam_end"] = "The exam is over",
	["notify.passed"] = "You passed: {grade}",
	["notify.failed"] = "You failed: {grade}",
	["notify.week_done"] = "Finals Week survived",
	["notify.expelled"] = "The class was expelled",
	["notify.credits"] = "+{n} credits",
	["notify.locker"] = "You found: {item}",
	["notify.locker_empty"] = "The locker is empty",
	["notify.locker_wait"] = "That locker just closed",
	["notify.hit"] = "A paper ball hit you",
	["notify.waiting"] = "Waiting for more students",
	["notify.seat"] = "Your desk is row {row}, seat {seat}",
	-- Pasillo: pelota y canasta
	["ball.grab"] = "Grab the ball",
	["ball.throw"] = "Click to shoot",
	["ball.hit"] = "{name} beaned you",
	["ball.basket"] = "{name} scored! +{n}",
	["ball.taken"] = "Somebody else has the ball",
	["ball.score"] = "Baskets: {n}",
	-- Grafiti
	["paint.title"] = "Spray",
	["paint.hint"] = "Hold click to paint - wheel changes size",
	["paint.wall"] = "You can't paint that",
	["paint.seen"] = "Painting in class? Really?",
	["paint.color"] = "Colour",
	["paint.size"] = "Size",
	["paint.clear"] = "Erase",
	-- Herramientas de comunicacion
	["item.walkie"] = "Walkie-talkie",
	["item.prismaticos"] = "Binoculars",
	["item.celular"] = "Phone",
	["item.libro"] = "Textbook",
	["item.pelota"] = "Basketball",
	["item.aerosol"] = "Spray can",
	["item.desc_walkie"] = "Talk to every other walkie in the school",
	["item.desc_prismaticos"] = "Zoom in and read a sheet from across the room",
	["item.desc_celular"] = "Whispers an answer to one classmate nearby",
	["item.desc_libro"] = "Read it at recess: you learn {n} answers",
	["item.desc_pelota"] = "It is a basketball. There is a hoop.",
	["item.desc_aerosol"] = "Paint on any wall in the school",
	-- Radio y celular
	["radio.title"] = "Walkie-talkie",
	["radio.placeholder"] = "Question 4 is C",
	["radio.send"] = "Transmit",
	["radio.sent"] = "Transmitted to {n} walkies",
	["radio.nobody"] = "Nobody else has a walkie",
	["radio.heard"] = "[radio] {name}: {text}",
	["radio.phone"] = "[phone] {name}: {text}",
	["radio.need_tool"] = "You need a walkie-talkie in your hand",
	["radio.too_long"] = "That message is too long",
	-- Prismaticos
	["zoom.on"] = "Binoculars: Q reads the sheet you are aiming at",
	["zoom.no_target"] = "There is no sheet in your sights",
	["zoom.read"] = "You read question {i} from over there",
	-- Libros y empollones
	["book.read"] = "Read the textbook",
	["book.learned"] = "You learned {n} answers",
	["book.none"] = "You are not holding a textbook",
	["book.too_far"] = "Too far away",
	["book.passed"] = "You handed the book to {name}",
	["book.received"] = "{name} handed you a textbook",
	["book.busy"] = "You already read that one",
	["book.only_recess"] = "There is no time to read now",
	["nerd.ask"] = "Ask for answers",
	["nerd.gave"] = "{name} gives you question {i}",
	["nerd.refused"] = "{name} says no",
	["nerd.wait"] = "{name} is not talking to you right now",
	["nerd.dropped"] = "{name} drops a cheat sheet",
	-- Nocaut
	["ko.push"] = "You shoved {name}",
	["ko.down"] = "{name} is on the floor",
	["ko.you"] = "You got knocked down",
	["ko.nobody"] = "Nobody within reach",
	["ko.hint"] = "G shoves - three shoves and they go down",
	["ko.in_class"] = "In the middle of the exam?",
	-- La goma del profesor
	["eraser.thrown"] = "{teacher} throws an eraser",
	["eraser.hit"] = "The eraser got you",
	["eraser.miss"] = "The eraser whistled past",
	-- Boletin
	["report.title"] = "Report card",
	["report.class_passed"] = "The class passed: {n} average",
	["report.class_failed"] = "The class failed: {n} average",
	["report.day"] = "Day {n}",
	["report.exam"] = "Exam",
	["report.behaviour"] = "Behaviour",
	["report.final"] = "Final",
	["report.correct"] = "{ok} of {n} correct",
	["report.punishments"] = "{n} punishments",
	["report.fails"] = "Failed days: {n}/{max}",
	["report.week"] = "Finals Week - final average",
	["report.next"] = "Next day starts in {s}s",
	["report.survived"] = "You made it through the week",
	["report.expelled"] = "Too many fails. Class expelled.",
	-- Menu
	["menu.title"] = "FINALS WEEK",
	["menu.subtitle"] = "Five days. One teacher. Do not get caught.",
	["menu.play"] = "Play",
	["menu.rooms"] = "Rooms",
	["menu.settings"] = "Settings",
	["menu.credits"] = "Credits",
	["menu.shop"] = "Store",
	["menu.back"] = "Back",
	["menu.close"] = "Close",
	["menu.solo"] = "Solo",
	["menu.solo_desc"] = "Your own classroom, nobody else",
	["menu.friends"] = "With friends",
	["menu.friends_desc"] = "Private room with a code",
	["menu.public"] = "Public class",
	["menu.public_desc"] = "Join whoever is playing",
	["menu.brightness"] = "Brightness",
	["menu.volume"] = "Volume",
	["menu.music"] = "Music",
	["menu.language"] = "Language",
	["menu.sensitivity"] = "Camera sensitivity",
	["menu.shop_desc"] = "Spend what you earned on the exam",
	["menu.settings_desc"] = "Brightness, volume and sensitivity",
	["menu.credits_desc"] = "Who made this and with what",
	-- Salas
	["room.title"] = "Rooms",
	["room.search"] = "Search a room",
	["room.create"] = "Create room",
	["room.name"] = "Room name",
	["room.password"] = "Password (optional)",
	["room.capacity"] = "Capacity: {n}",
	["room.join"] = "Join",
	["room.locked"] = "Locked",
	["room.players"] = "{n}/{max}",
	["room.empty"] = "No open rooms",
	["room.created"] = "Room {code} created",
	["room.wrong_password"] = "Wrong password",
	["room.full"] = "The room is full",
	["room.gone"] = "That room no longer exists",
	["room.unavailable"] = "Rooms only work in a published game",
	["room.code"] = "Code",
	["room.invite"] = "Invite friends",
	["room.refresh"] = "Refresh",
	-- Creditos
	["credits.title"] = "Credits",
	["credits.body"] = "Built from scratch in Luau: map, teacher AI, exams, cheating and economy.",
	["credits.design"] = "Design and code",
	["credits.thanks"] = "Cheating is not the answer. Studying is. But this is a game.",
	-- Errores
	["error.generic"] = "Something went wrong",
	["error.not_seated"] = "Sit at your desk first",
	["error.phase"] = "Not right now",
	["error.save"] = "Your progress could not be saved",
}

local es: { [string]: string } = {
	-- Fases del dia
	["phase.espera"] = "Esperando alumnos",
	["phase.recreo"] = "Recreo",
	["phase.examen"] = "Examen",
	["phase.boletin"] = "Boletines",
	["phase.intermedio"] = "Entre clases",
	["phase.semana"] = "Semana Final",
	["day.lunes"] = "Lunes",
	["day.martes"] = "Martes",
	["day.miercoles"] = "Miercoles",
	["day.jueves"] = "Jueves",
	["day.viernes"] = "Viernes",
	-- HUD
	["hud.day"] = "Dia {n} - {day}",
	["hud.suspicion"] = "SOSPECHA",
	["hud.grade"] = "NOTA DEL TRIMESTRE",
	["hud.credits"] = "CREDITOS",
	["hud.objective"] = "OBJETIVO",
	["hud.close_call"] = "EL PROFESOR TE ESTA MIRANDO",
	["hud.locked"] = "Puertas trabadas",
	["hud.hint_recess"] = "Agarra lo que necesites antes de la campana",
	["hud.hint_exam"] = "Responde la hoja de tu pupitre",
	["hud.hint_report"] = "Salieron los boletines",
	["hud.detention"] = "Castigo: {s}s",
	["hud.cone"] = "Cono de la verguenza: {s}s",
	["hud.keys"] = "E interactuar - Q espiar - R soplar - F lanzar - G empujar - B tirar - Z zoom",
	-- Examen
	["exam.title"] = "Examen - {subject}",
	["exam.question"] = "Pregunta {i} de {n}",
	["exam.progress"] = "{done}/{total} respondidas",
	["exam.answered"] = "Respondida",
	["exam.blank"] = "En blanco",
	["exam.correct"] = "Correcta",
	["exam.wrong"] = "Incorrecta",
	["exam.type_prompt"] = "Escribi la secuencia",
	["exam.type_fail"] = "La erraste al escribir",
	["exam.time_up"] = "Se acabo el tiempo",
	["exam.not_started"] = "El examen no empezo",
	["exam.prev"] = "Anterior",
	["exam.next"] = "Siguiente",
	["topic.math"] = "Matematica",
	["topic.history"] = "Historia",
	["topic.science"] = "Ciencias",
	["topic.language"] = "Lengua",
	["topic.geography"] = "Geografia",
	-- Trampas
	["cheat.peek"] = "Espiar la hoja del de al lado",
	["cheat.peek_ok"] = "Copiaste la pregunta {i}",
	["cheat.peek_fail"] = "No llegaste a leer nada",
	["cheat.peek_none"] = "No hay nadie lo bastante cerca",
	["cheat.whisper"] = "Soplar una respuesta",
	["cheat.whisper_sent"] = "Soplaste la pregunta {i}",
	["cheat.whisper_got"] = "{name} sopla: la {i} es {opt}",
	["cheat.sheet_used"] = "Chuleta: {n} respuestas reveladas",
	["cheat.sheet_empty"] = "La chuleta ya no da mas",
	["stash.drawer"] = "Le robaste al cajon: {n} respuestas",
	["stash.alcove"] = "La hoja de respuestas: aprendiste {n}",
	["stash.empty"] = "Ahi adentro no hay nada",
	["stash.locked"] = "La biblioteca cierra durante el examen",
	["stash.cooling"] = "Para un poco",
	["cheat.cooldown"] = "Espera un momento",
	["cheat.seen"] = "El profesor te vio",
	["cheat.none"] = "No tenes nada para usar",
	-- Objetos
	["item.nota"] = "Nota",
	["item.avion"] = "Avioncito",
	["item.bolita"] = "Bolita de papel",
	["item.chuleta"] = "Chuleta",
	["item.gorra"] = "Gorra",
	["item.mochila"] = "Mochila",
	["item.anteojos"] = "Anteojos",
	["item.campera"] = "Campera",
	["item.desc_nota"] = "Escribi una respuesta y lanzasela a un companero",
	["item.desc_avion"] = "Vuela mas lejos y mas derecho que la bolita",
	["item.desc_bolita"] = "Lanzala lejos: el profe va hacia el ruido",
	["item.desc_chuleta"] = "Revela {n} respuestas del examen actual",
	["item.desc_gorra"] = "Una gorra. No hace nada. Queda bien.",
	["item.desc_mochila"] = "Mochila de colegio clasica",
	["item.desc_anteojos"] = "Parece que estudias",
	["item.desc_campera"] = "Campera del colegio con el escudo",
	-- Notas de papel
	["note.write"] = "Escribi tu nota",
	["note.placeholder"] = "la 3 es B, la 5 es A...",
	["note.throw"] = "Apunta y hace clic para lanzar",
	["note.sent"] = "Nota lanzada",
	["note.received"] = "{name} te paso una nota",
	["note.empty"] = "La nota esta en blanco",
	["note.read"] = "La nota dice:",
	-- Tienda
	["shop.title"] = "Tienda del colegio",
	["shop.buy"] = "Comprar",
	["shop.owned"] = "Comprado",
	["shop.locked"] = "Bloqueado",
	["shop.need_weeks"] = "Primero sobrevivi {n} semanas finales",
	["shop.need_grade"] = "Primero llega a un promedio de {n}",
	["shop.equip"] = "Equipar",
	["shop.equipped"] = "Equipado",
	["shop.cannot"] = "No te alcanzan los creditos",
	["shop.bought"] = "Compraste {item}",
	["shop.closed"] = "La tienda solo abre en el recreo",
	["shop.tab_items"] = "Objetos",
	["shop.tab_looks"] = "Estetica",
	["shop.price"] = "{n} cr",
	-- El profesor
	["teacher.greet"] = "Sientense. Ya.",
	["teacher.start_exam"] = "Tienen {s} segundos. Nadie habla.",
	["teacher.silence"] = "Silencio.",
	["teacher.sit_down"] = "A tu asiento.",
	["teacher.eyes_on_paper"] = "Los ojos en tu hoja.",
	["teacher.caught"] = "Eso lo vi, {name}.",
	["teacher.warning"] = "Ultima advertencia.",
	["teacher.blackboard"] = "Copien esto.",
	["teacher.time_left"] = "Quedan {s} segundos.",
	["teacher.finish"] = "Lapices abajo. Hojas arriba.",
	["teacher.noise"] = "Quien tiro eso?",
	-- Castigos
	["punish.cone"] = "{name} se gano el cono de la verguenza",
	["punish.grade"] = "-{n} puntos de tu nota",
	["punish.detention"] = "{name} fue a la sala de castigo",
	["punish.warned"] = "Ultima advertencia",
	["punish.back"] = "Volviste al aula",
	-- Avisos
	["notify.bell"] = "Sono la campana",
	["notify.bell_soon"] = "La campana suena en {s}s",
	["notify.doors_locked"] = "Se trabaron las puertas del aula",
	["notify.exam_start"] = "Empezo el examen",
	["notify.exam_end"] = "Se termino el examen",
	["notify.passed"] = "Aprobaste: {grade}",
	["notify.failed"] = "Desaprobaste: {grade}",
	["notify.week_done"] = "Sobreviviste a la Semana Final",
	["notify.expelled"] = "Expulsaron al curso",
	["notify.credits"] = "+{n} creditos",
	["notify.locker"] = "Encontraste: {item}",
	["notify.locker_empty"] = "El casillero esta vacio",
	["notify.locker_wait"] = "Ese casillero se acaba de cerrar",
	["notify.hit"] = "Te pego una bolita de papel",
	["notify.waiting"] = "Esperando mas alumnos",
	["notify.seat"] = "Tu pupitre es fila {row}, asiento {seat}",
	-- Pasillo: pelota y canasta
	["ball.grab"] = "Agarrar la pelota",
	["ball.throw"] = "Clic para tirar",
	["ball.hit"] = "{name} te dio un pelotazo",
	["ball.basket"] = "Canasta de {name}! +{n}",
	["ball.taken"] = "La pelota la tiene otro",
	["ball.score"] = "Canastas: {n}",
	-- Grafiti
	["paint.title"] = "Aerosol",
	["paint.hint"] = "Manten el clic para pintar - la rueda cambia el tamano",
	["paint.wall"] = "Eso no se puede pintar",
	["paint.seen"] = "Pintando en el aula? En serio?",
	["paint.color"] = "Color",
	["paint.size"] = "Tamano",
	["paint.clear"] = "Borrar",
	-- Herramientas de comunicacion
	["item.walkie"] = "Walkie-talkie",
	["item.prismaticos"] = "Prismaticos",
	["item.celular"] = "Celular",
	["item.libro"] = "Libro de texto",
	["item.pelota"] = "Pelota",
	["item.aerosol"] = "Aerosol",
	["item.desc_walkie"] = "Hablas con todos los walkies del colegio",
	["item.desc_prismaticos"] = "Haces zoom y lees una hoja desde lejos",
	["item.desc_celular"] = "Le pasa una respuesta a un companero cercano",
	["item.desc_libro"] = "Leelo en el recreo: aprendes {n} respuestas",
	["item.desc_pelota"] = "Es una pelota de basquet. Hay un aro.",
	["item.desc_aerosol"] = "Pinta cualquier pared del colegio",
	-- Radio y celular
	["radio.title"] = "Walkie-talkie",
	["radio.placeholder"] = "la 4 es C",
	["radio.send"] = "Transmitir",
	["radio.sent"] = "Transmitido a {n} walkies",
	["radio.nobody"] = "Nadie mas tiene walkie",
	["radio.heard"] = "[radio] {name}: {text}",
	["radio.phone"] = "[celular] {name}: {text}",
	["radio.need_tool"] = "Necesitas el walkie en la mano",
	["radio.too_long"] = "Ese mensaje es muy largo",
	-- Prismaticos
	["zoom.on"] = "Prismaticos: Q lee la hoja que estas apuntando",
	["zoom.no_target"] = "No hay ninguna hoja en la mira",
	["zoom.read"] = "Leiste la pregunta {i} desde lejos",
	-- Libros y empollones
	["book.read"] = "Leer el libro",
	["book.learned"] = "Aprendiste {n} respuestas",
	["book.none"] = "No llevas ningun libro",
	["book.too_far"] = "Esta demasiado lejos",
	["book.passed"] = "Le pasaste el libro a {name}",
	["book.received"] = "{name} te paso un libro",
	["book.busy"] = "Ese ya lo leiste",
	["book.only_recess"] = "Ahora no hay tiempo de leer",
	["nerd.ask"] = "Pedir respuestas",
	["nerd.gave"] = "{name} te pasa la {i}",
	["nerd.refused"] = "{name} te dice que no",
	["nerd.wait"] = "{name} no te habla por ahora",
	["nerd.dropped"] = "A {name} se le cae una chuleta",
	-- Nocaut
	["ko.push"] = "Empujaste a {name}",
	["ko.down"] = "{name} quedo en el piso",
	["ko.you"] = "Te dejaron en el piso",
	["ko.nobody"] = "No hay nadie al alcance",
	["ko.hint"] = "G empuja - tres empujones y cae",
	["ko.in_class"] = "En pleno examen?",
	-- La goma del profesor
	["eraser.thrown"] = "{teacher} te tira una goma",
	["eraser.hit"] = "Te pego la goma",
	["eraser.miss"] = "La goma paso silbando",
	-- Boletin
	["report.title"] = "Boletin",
	["report.class_passed"] = "El curso aprobo: promedio {n}",
	["report.class_failed"] = "El curso desaprobo: promedio {n}",
	["report.day"] = "Dia {n}",
	["report.exam"] = "Examen",
	["report.behaviour"] = "Conducta",
	["report.final"] = "Final",
	["report.correct"] = "{ok} de {n} correctas",
	["report.punishments"] = "{n} castigos",
	["report.fails"] = "Dias desaprobados: {n}/{max}",
	["report.week"] = "Semana Final - promedio final",
	["report.next"] = "El proximo dia empieza en {s}s",
	["report.survived"] = "Zafaste toda la semana",
	["report.expelled"] = "Demasiados suspensos. Curso expulsado.",
	-- Menu
	["menu.title"] = "SEMANA FINAL",
	["menu.subtitle"] = "Cinco dias. Un profesor. Que no te pillen.",
	["menu.play"] = "Jugar",
	["menu.rooms"] = "Salas",
	["menu.settings"] = "Ajustes",
	["menu.credits"] = "Creditos",
	["menu.shop"] = "Tienda",
	["menu.back"] = "Volver",
	["menu.close"] = "Cerrar",
	["menu.solo"] = "Solo",
	["menu.solo_desc"] = "Tu propia aula, sin nadie mas",
	["menu.friends"] = "Con amigos",
	["menu.friends_desc"] = "Sala privada con codigo",
	["menu.public"] = "Curso publico",
	["menu.public_desc"] = "Entra con quien este jugando",
	["menu.brightness"] = "Brillo",
	["menu.volume"] = "Volumen",
	["menu.music"] = "Musica",
	["menu.language"] = "Idioma",
	["menu.sensitivity"] = "Sensibilidad de camara",
	["menu.shop_desc"] = "Gasta lo que sacaste en el examen",
	["menu.settings_desc"] = "Brillo, volumen y sensibilidad",
	["menu.credits_desc"] = "Quien hizo esto y con que",
	-- Salas
	["room.title"] = "Salas",
	["room.search"] = "Buscar una sala",
	["room.create"] = "Crear sala",
	["room.name"] = "Nombre de la sala",
	["room.password"] = "Contrasena (opcional)",
	["room.capacity"] = "Capacidad: {n}",
	["room.join"] = "Entrar",
	["room.locked"] = "Con clave",
	["room.players"] = "{n}/{max}",
	["room.empty"] = "No hay salas abiertas",
	["room.created"] = "Sala {code} creada",
	["room.wrong_password"] = "Contrasena incorrecta",
	["room.full"] = "La sala esta llena",
	["room.gone"] = "Esa sala ya no existe",
	["room.unavailable"] = "Las salas solo andan en un juego publicado",
	["room.code"] = "Codigo",
	["room.invite"] = "Invitar amigos",
	["room.refresh"] = "Actualizar",
	-- Creditos
	["credits.title"] = "Creditos",
	["credits.body"] = "Hecho de cero en Luau: mapa, IA del profesor, examenes, trampas y economia.",
	["credits.design"] = "Diseno y codigo",
	["credits.thanks"] = "Copiarse no es la solucion. Estudiar si. Pero esto es un juego.",
	-- Errores
	["error.generic"] = "Algo salio mal",
	["error.not_seated"] = "Primero sentate en tu pupitre",
	["error.phase"] = "Ahora no",
	["error.save"] = "No se pudo guardar tu progreso",
}

local pt: { [string]: string } = {
	-- Fases del dia
	["phase.espera"] = "Aguardando alunos",
	["phase.recreo"] = "Recreio",
	["phase.examen"] = "Prova",
	["phase.boletin"] = "Boletins",
	["phase.intermedio"] = "Entre aulas",
	["phase.semana"] = "Semana Final",
	["day.lunes"] = "Segunda",
	["day.martes"] = "Terca",
	["day.miercoles"] = "Quarta",
	["day.jueves"] = "Quinta",
	["day.viernes"] = "Sexta",
	-- HUD
	["hud.day"] = "Dia {n} - {day}",
	["hud.suspicion"] = "SUSPEITA",
	["hud.grade"] = "NOTA DO TRIMESTRE",
	["hud.credits"] = "CREDITOS",
	["hud.objective"] = "OBJETIVO",
	["hud.close_call"] = "O PROFESSOR ESTA TE OLHANDO",
	["hud.locked"] = "Portas trancadas",
	["hud.hint_recess"] = "Pegue o que precisar antes do sinal",
	["hud.hint_exam"] = "Responda a folha na sua carteira",
	["hud.hint_report"] = "Sairam os boletins",
	["hud.detention"] = "Castigo: {s}s",
	["hud.cone"] = "Cone da vergonha: {s}s",
	["hud.keys"] = "E interagir - Q espiar - R soprar - F arremessar - G empurrar - B arremessar - Z zoom",
	-- Examen
	["exam.title"] = "Prova - {subject}",
	["exam.question"] = "Questao {i} de {n}",
	["exam.progress"] = "{done}/{total} respondidas",
	["exam.answered"] = "Respondida",
	["exam.blank"] = "Em branco",
	["exam.correct"] = "Correta",
	["exam.wrong"] = "Errada",
	["exam.type_prompt"] = "Digite a sequencia",
	["exam.type_fail"] = "Voce errou ao digitar",
	["exam.time_up"] = "Acabou o tempo",
	["exam.not_started"] = "A prova nao comecou",
	["exam.prev"] = "Anterior",
	["exam.next"] = "Proxima",
	["topic.math"] = "Matematica",
	["topic.history"] = "Historia",
	["topic.science"] = "Ciencias",
	["topic.language"] = "Lingua",
	["topic.geography"] = "Geografia",
	-- Trampas
	["cheat.peek"] = "Espiar a folha do colega",
	["cheat.peek_ok"] = "Voce copiou a questao {i}",
	["cheat.peek_fail"] = "Voce nao conseguiu ler nada",
	["cheat.peek_none"] = "Nao ha ninguem perto o suficiente",
	["cheat.whisper"] = "Soprar uma resposta",
	["cheat.whisper_sent"] = "Voce soprou a questao {i}",
	["cheat.whisper_got"] = "{name} sopra: a {i} e {opt}",
	["cheat.sheet_used"] = "Cola: {n} respostas reveladas",
	["cheat.sheet_empty"] = "A cola ja acabou",
	["stash.drawer"] = "Voce roubou a gaveta: {n} respostas",
	["stash.alcove"] = "O gabarito: {n} respostas aprendidas",
	["stash.empty"] = "Nao tem nada ai dentro",
	["stash.locked"] = "A biblioteca fecha durante a prova",
	["stash.cooling"] = "Calma ai",
	["cheat.cooldown"] = "Espere um pouco",
	["cheat.seen"] = "O professor te viu",
	["cheat.none"] = "Voce nao tem nada para usar",
	-- Objetos
	["item.nota"] = "Bilhete",
	["item.avion"] = "Aviaozinho",
	["item.bolita"] = "Bolinha de papel",
	["item.chuleta"] = "Cola",
	["item.gorra"] = "Bone",
	["item.mochila"] = "Mochila",
	["item.anteojos"] = "Oculos",
	["item.campera"] = "Jaqueta",
	["item.desc_nota"] = "Escreva uma resposta e jogue para um colega",
	["item.desc_avion"] = "Voa mais longe e mais reto que a bolinha",
	["item.desc_bolita"] = "Jogue longe: o professor vai ate o barulho",
	["item.desc_chuleta"] = "Revela {n} respostas da prova atual",
	["item.desc_gorra"] = "Um bone. Nao faz nada. Fica bem.",
	["item.desc_mochila"] = "Mochila escolar classica",
	["item.desc_anteojos"] = "Parece que voce estuda",
	["item.desc_campera"] = "Jaqueta do colegio com o brasao",
	-- Notas de papel
	["note.write"] = "Escreva seu bilhete",
	["note.placeholder"] = "a 3 e B, a 5 e A...",
	["note.throw"] = "Mire e clique para arremessar",
	["note.sent"] = "Bilhete arremessado",
	["note.received"] = "{name} te passou um bilhete",
	["note.empty"] = "O bilhete esta em branco",
	["note.read"] = "O bilhete diz:",
	-- Tienda
	["shop.title"] = "Loja da escola",
	["shop.buy"] = "Comprar",
	["shop.owned"] = "Comprado",
	["shop.locked"] = "Bloqueado",
	["shop.need_weeks"] = "Sobreviva {n} semanas de prova antes",
	["shop.need_grade"] = "Chegue a uma media de {n} antes",
	["shop.equip"] = "Equipar",
	["shop.equipped"] = "Equipado",
	["shop.cannot"] = "Creditos insuficientes",
	["shop.bought"] = "Voce comprou {item}",
	["shop.closed"] = "A loja so abre no recreio",
	["shop.tab_items"] = "Objetos",
	["shop.tab_looks"] = "Estetica",
	["shop.price"] = "{n} cr",
	-- El profesor
	["teacher.greet"] = "Sentem-se. Agora.",
	["teacher.start_exam"] = "Voces tem {s} segundos. Ninguem fala.",
	["teacher.silence"] = "Silencio.",
	["teacher.sit_down"] = "Volte para o seu lugar.",
	["teacher.eyes_on_paper"] = "Olhos na sua folha.",
	["teacher.caught"] = "Eu vi isso, {name}.",
	["teacher.warning"] = "Ultimo aviso.",
	["teacher.blackboard"] = "Copiem isto.",
	["teacher.time_left"] = "Faltam {s} segundos.",
	["teacher.finish"] = "Lapis na mesa. Folhas para cima.",
	["teacher.noise"] = "Quem jogou isso?",
	-- Castigos
	["punish.cone"] = "{name} ganhou o cone da vergonha",
	["punish.grade"] = "-{n} pontos da sua nota",
	["punish.detention"] = "{name} foi para a sala de castigo",
	["punish.warned"] = "Ultimo aviso",
	["punish.back"] = "Voce voltou para a sala",
	-- Avisos
	["notify.bell"] = "O sinal tocou",
	["notify.bell_soon"] = "O sinal toca em {s}s",
	["notify.doors_locked"] = "As portas da sala trancaram",
	["notify.exam_start"] = "A prova comecou",
	["notify.exam_end"] = "A prova acabou",
	["notify.passed"] = "Voce passou: {grade}",
	["notify.failed"] = "Voce reprovou: {grade}",
	["notify.week_done"] = "Voce sobreviveu a Semana Final",
	["notify.expelled"] = "A turma foi expulsa",
	["notify.credits"] = "+{n} creditos",
	["notify.locker"] = "Voce achou: {item}",
	["notify.locker_empty"] = "O armario esta vazio",
	["notify.locker_wait"] = "Esse armario acabou de fechar",
	["notify.hit"] = "Uma bolinha de papel te acertou",
	["notify.waiting"] = "Aguardando mais alunos",
	["notify.seat"] = "Sua carteira e fila {row}, lugar {seat}",
	-- Pasillo: pelota y canasta
	["ball.grab"] = "Pegar a bola",
	["ball.throw"] = "Clique para arremessar",
	["ball.hit"] = "{name} te acertou com a bola",
	["ball.basket"] = "Cesta de {name}! +{n}",
	["ball.taken"] = "Outra pessoa esta com a bola",
	["ball.score"] = "Cestas: {n}",
	-- Grafiti
	["paint.title"] = "Spray",
	["paint.hint"] = "Segure o clique para pintar - a roda muda o tamanho",
	["paint.wall"] = "Isso nao da para pintar",
	["paint.seen"] = "Pintando na sala? Serio?",
	["paint.color"] = "Cor",
	["paint.size"] = "Tamanho",
	["paint.clear"] = "Apagar",
	-- Herramientas de comunicacion
	["item.walkie"] = "Walkie-talkie",
	["item.prismaticos"] = "Binoculos",
	["item.celular"] = "Celular",
	["item.libro"] = "Livro didatico",
	["item.pelota"] = "Bola",
	["item.aerosol"] = "Lata de spray",
	["item.desc_walkie"] = "Fala com todos os walkies da escola",
	["item.desc_prismaticos"] = "Da zoom e le uma folha de longe",
	["item.desc_celular"] = "Passa uma resposta para um colega perto",
	["item.desc_libro"] = "Leia no recreio: voce aprende {n} respostas",
	["item.desc_pelota"] = "E uma bola de basquete. Tem uma cesta.",
	["item.desc_aerosol"] = "Pinta qualquer parede da escola",
	-- Radio y celular
	["radio.title"] = "Walkie-talkie",
	["radio.placeholder"] = "a 4 e C",
	["radio.send"] = "Transmitir",
	["radio.sent"] = "Transmitido para {n} walkies",
	["radio.nobody"] = "Ninguem mais tem walkie",
	["radio.heard"] = "[radio] {name}: {text}",
	["radio.phone"] = "[celular] {name}: {text}",
	["radio.need_tool"] = "Voce precisa do walkie na mao",
	["radio.too_long"] = "Essa mensagem e longa demais",
	-- Prismaticos
	["zoom.on"] = "Binoculos: Q le a folha que voce esta mirando",
	["zoom.no_target"] = "Nao ha folha na mira",
	["zoom.read"] = "Voce leu a questao {i} de longe",
	-- Libros y empollones
	["book.read"] = "Ler o livro",
	["book.learned"] = "Voce aprendeu {n} respostas",
	["book.none"] = "Voce nao esta com nenhum livro",
	["book.too_far"] = "Esta longe demais",
	["book.passed"] = "Voce passou o livro para {name}",
	["book.received"] = "{name} te passou um livro",
	["book.busy"] = "Esse voce ja leu",
	["book.only_recess"] = "Agora nao da tempo de ler",
	["nerd.ask"] = "Pedir respostas",
	["nerd.gave"] = "{name} te passa a {i}",
	["nerd.refused"] = "{name} diz que nao",
	["nerd.wait"] = "{name} nao fala com voce agora",
	["nerd.dropped"] = "{name} deixa cair uma cola",
	-- Nocaut
	["ko.push"] = "Voce empurrou {name}",
	["ko.down"] = "{name} ficou no chao",
	["ko.you"] = "Voce foi derrubado",
	["ko.nobody"] = "Nao ha ninguem ao alcance",
	["ko.hint"] = "G empurra - tres empurroes e cai",
	["ko.in_class"] = "No meio da prova?",
	-- La goma del profesor
	["eraser.thrown"] = "{teacher} joga uma borracha",
	["eraser.hit"] = "A borracha te acertou",
	["eraser.miss"] = "A borracha passou assobiando",
	-- Boletin
	["report.title"] = "Boletim",
	["report.class_passed"] = "A turma passou: media {n}",
	["report.class_failed"] = "A turma reprovou: media {n}",
	["report.day"] = "Dia {n}",
	["report.exam"] = "Prova",
	["report.behaviour"] = "Conduta",
	["report.final"] = "Final",
	["report.correct"] = "{ok} de {n} corretas",
	["report.punishments"] = "{n} castigos",
	["report.fails"] = "Dias reprovados: {n}/{max}",
	["report.week"] = "Semana Final - media final",
	["report.next"] = "O proximo dia comeca em {s}s",
	["report.survived"] = "Voce escapou a semana toda",
	["report.expelled"] = "Reprovacoes demais. Turma expulsa.",
	-- Menu
	["menu.title"] = "SEMANA FINAL",
	["menu.subtitle"] = "Cinco dias. Um professor. Nao seja pego.",
	["menu.play"] = "Jogar",
	["menu.rooms"] = "Salas",
	["menu.settings"] = "Ajustes",
	["menu.credits"] = "Creditos",
	["menu.shop"] = "Loja",
	["menu.back"] = "Voltar",
	["menu.close"] = "Fechar",
	["menu.solo"] = "Sozinho",
	["menu.solo_desc"] = "Sua propria sala, sem mais ninguem",
	["menu.friends"] = "Com amigos",
	["menu.friends_desc"] = "Sala privada com codigo",
	["menu.public"] = "Turma publica",
	["menu.public_desc"] = "Entre com quem estiver jogando",
	["menu.brightness"] = "Brilho",
	["menu.volume"] = "Volume",
	["menu.music"] = "Musica",
	["menu.language"] = "Idioma",
	["menu.sensitivity"] = "Sensibilidade da camera",
	["menu.shop_desc"] = "Gaste o que voce ganhou na prova",
	["menu.settings_desc"] = "Brilho, volume e sensibilidade",
	["menu.credits_desc"] = "Quem fez isto e com o que",
	-- Salas
	["room.title"] = "Salas",
	["room.search"] = "Buscar uma sala",
	["room.create"] = "Criar sala",
	["room.name"] = "Nome da sala",
	["room.password"] = "Senha (opcional)",
	["room.capacity"] = "Capacidade: {n}",
	["room.join"] = "Entrar",
	["room.locked"] = "Com senha",
	["room.players"] = "{n}/{max}",
	["room.empty"] = "Nenhuma sala aberta",
	["room.created"] = "Sala {code} criada",
	["room.wrong_password"] = "Senha incorreta",
	["room.full"] = "A sala esta cheia",
	["room.gone"] = "Essa sala ja nao existe",
	["room.unavailable"] = "As salas so funcionam num jogo publicado",
	["room.code"] = "Codigo",
	["room.invite"] = "Convidar amigos",
	["room.refresh"] = "Atualizar",
	-- Creditos
	["credits.title"] = "Creditos",
	["credits.body"] = "Feito do zero em Luau: mapa, IA do professor, provas, trapacas e economia.",
	["credits.design"] = "Design e codigo",
	["credits.thanks"] = "Colar nao e a solucao. Estudar e. Mas isto e um jogo.",
	-- Errores
	["error.generic"] = "Algo deu errado",
	["error.not_seated"] = "Primeiro sente na sua carteira",
	["error.phase"] = "Agora nao",
	["error.save"] = "Nao foi possivel salvar seu progresso",
}

local locales: { [string]: { [string]: string } } = { en = en, es = es, pt = pt }

local current = en
local currentId = "en"

--- "es-ar" -> "es". Si el idioma no esta traducido, cae en ingles.
function Strings.setLocale(localeId: string?)
	local short = string.lower(string.sub(localeId or "en", 1, 2))
	current = locales[short] or en
	currentId = locales[short] and short or "en"
end

function Strings.locale(): string
	return currentId
end

--- Devuelve el texto de una clave, reemplazando {marcadores} por args.
function Strings.get(key: string, args: { [string]: any }?): string
	local text = current[key] or en[key]
	if not text then
		return key
	end
	if args then
		text = (string.gsub(text, "{(%w+)}", function(name: string): string
			local value = args[name]
			return value ~= nil and tostring(value) or ("{" .. name .. "}")
		end))
	end
	return text
end

--- Para textos que el servidor manda como "@clave" (elecciones, listas).
function Strings.resolve(text: string): string
	if string.sub(text, 1, 1) == "@" then
		return Strings.get(string.sub(text, 2))
	end
	return text
end

--- Un paquete { key = ..., args = ... } que viaja por la red.
export type Packet = { key: string, args: { [string]: any }? }

function Strings.render(packet: Packet?): string
	if not packet then
		return ""
	end
	return Strings.get(packet.key, packet.args)
end

return Strings
